import type * as Monaco from "monaco-editor";
import type { ITheme } from "@xterm/xterm";
import type { ThemeMode } from "@/stores/theme";

export const MONACO_THEME: Record<ThemeMode, string> = { daylight: "fjord-daylight", dusk: "fjord-dusk" };

/** Monaco themes matching the Fjord palette. Syntax colors all clear 4.5:1 on the editor background. */
export function defineFjordThemes(monaco: typeof Monaco) {
  monaco.editor.defineTheme("fjord-daylight", {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "2E3D45" },
      { token: "comment", foreground: "617380", fontStyle: "italic" },
      { token: "keyword", foreground: "1D6A8F" },
      { token: "storage", foreground: "1D6A8F" },
      { token: "string", foreground: "56692F" },
      { token: "string.escape", foreground: "2F6F6A" },
      { token: "number", foreground: "7A4F7D" },
      { token: "constant", foreground: "7A4F7D" },
      { token: "regexp", foreground: "7A4F7D" },
      { token: "type", foreground: "2F6F6A" },
      { token: "type.identifier", foreground: "2F6F6A" },
      { token: "function", foreground: "3E528F" },
      { token: "identifier", foreground: "2E3D45" },
      { token: "delimiter", foreground: "53656E" },
      { token: "operator", foreground: "53656E" },
      { token: "tag", foreground: "2D6177" },
      { token: "attribute.name", foreground: "2F6F6A" },
      { token: "attribute.value", foreground: "56692F" },
      { token: "metatag", foreground: "7A4F7D" },
      { token: "annotation", foreground: "7A4F7D" },
    ],
    colors: {
      "editor.background": "#F7F9F9",
      "editor.foreground": "#2E3D45",
      "editorLineNumber.foreground": "#8D9EA6",
      "editorLineNumber.activeForeground": "#2E3D45",
      "editor.lineHighlightBackground": "#EEF3F4",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#C4DAE4",
      "editor.inactiveSelectionBackground": "#D8E4E9",
      "editor.wordHighlightBackground": "#DCE7EC",
      "editorCursor.foreground": "#2D6177",
      "editorIndentGuide.background1": "#E1E8EB",
      "editorIndentGuide.activeBackground1": "#B9C7CD",
      "editorWhitespace.foreground": "#C9D3D8",
      "editorBracketMatch.background": "#DCE7EC",
      "editorBracketMatch.border": "#9AB7C4",
      "editorWidget.background": "#F7F9F9",
      "editorWidget.border": "#CFD9DD",
      "editorSuggestWidget.background": "#F7F9F9",
      "editorSuggestWidget.border": "#CFD9DD",
      "editorSuggestWidget.selectedBackground": "#DDE5E8",
      "editorHoverWidget.background": "#F7F9F9",
      "editorHoverWidget.border": "#CFD9DD",
      "editorError.foreground": "#A23C3C",
      "editorWarning.foreground": "#8A6A1E",
      "editorInfo.foreground": "#2D6177",
      "scrollbarSlider.background": "#53656E26",
      "scrollbarSlider.hoverBackground": "#53656E40",
      "scrollbarSlider.activeBackground": "#53656E55",
      focusBorder: "#2D6177",
    },
  });
  monaco.editor.defineTheme("fjord-dusk", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "D6DFE3" },
      { token: "comment", foreground: "7F909A", fontStyle: "italic" },
      { token: "keyword", foreground: "8DBBD0" },
      { token: "storage", foreground: "8DBBD0" },
      { token: "string", foreground: "A7BC79" },
      { token: "string.escape", foreground: "7FC1B8" },
      { token: "number", foreground: "C9A0CF" },
      { token: "constant", foreground: "C9A0CF" },
      { token: "regexp", foreground: "C9A0CF" },
      { token: "type", foreground: "7FC1B8" },
      { token: "type.identifier", foreground: "7FC1B8" },
      { token: "function", foreground: "AFC3F0" },
      { token: "identifier", foreground: "D6DFE3" },
      { token: "delimiter", foreground: "93A4AD" },
      { token: "operator", foreground: "93A4AD" },
      { token: "tag", foreground: "8DBBD0" },
      { token: "attribute.name", foreground: "7FC1B8" },
      { token: "attribute.value", foreground: "A7BC79" },
      { token: "metatag", foreground: "C9A0CF" },
      { token: "annotation", foreground: "C9A0CF" },
    ],
    colors: {
      "editor.background": "#1E272D",
      "editor.foreground": "#D6DFE3",
      "editorLineNumber.foreground": "#5F707A",
      "editorLineNumber.activeForeground": "#D6DFE3",
      "editor.lineHighlightBackground": "#232D34",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#35576A",
      "editor.inactiveSelectionBackground": "#2C414D",
      "editor.wordHighlightBackground": "#2C3E48",
      "editorCursor.foreground": "#8DBBD0",
      "editorIndentGuide.background1": "#2A353C",
      "editorIndentGuide.activeBackground1": "#45555E",
      "editorWhitespace.foreground": "#3A4850",
      "editorBracketMatch.background": "#2C3E48",
      "editorBracketMatch.border": "#5D8396",
      "editorWidget.background": "#1E272D",
      "editorWidget.border": "#2E3A41",
      "editorSuggestWidget.background": "#1E272D",
      "editorSuggestWidget.border": "#2E3A41",
      "editorSuggestWidget.selectedBackground": "#2A353C",
      "editorHoverWidget.background": "#1E272D",
      "editorHoverWidget.border": "#2E3A41",
      "editorError.foreground": "#E28B83",
      "editorWarning.foreground": "#D8B86A",
      "editorInfo.foreground": "#8DBBD0",
      "scrollbarSlider.background": "#93A4AD26",
      "scrollbarSlider.hoverBackground": "#93A4AD40",
      "scrollbarSlider.activeBackground": "#93A4AD55",
      focusBorder: "#8DBBD0",
    },
  });
}

/** xterm themes ("fjord-daylight" and "fjord-dusk"). ANSI colors are tuned to stay readable on each ground. */
export const XTERM_THEMES: Record<ThemeMode, ITheme> = {
  daylight: {
    background: "#F7F9F9",
    foreground: "#2E3D45",
    cursor: "#2D6177",
    cursorAccent: "#F7F9F9",
    selectionBackground: "#C4DAE4",
    black: "#2E3D45",
    red: "#A23C3C",
    green: "#56692F",
    yellow: "#80621A",
    blue: "#2D6177",
    magenta: "#7A4F7D",
    cyan: "#2F6F6A",
    white: "#6C7E87",
    brightBlack: "#617380",
    brightRed: "#B2463F",
    brightGreen: "#4F6B22",
    brightYellow: "#8A6A1E",
    brightBlue: "#3E528F",
    brightMagenta: "#8B4F8E",
    brightCyan: "#2C7A72",
    brightWhite: "#53656E",
  },
  dusk: {
    background: "#1E272D",
    foreground: "#D6DFE3",
    cursor: "#8DBBD0",
    cursorAccent: "#1E272D",
    selectionBackground: "#35576A",
    black: "#2A353C",
    red: "#E28B83",
    green: "#A7BC79",
    yellow: "#D8B86A",
    blue: "#8DBBD0",
    magenta: "#C9A0CF",
    cyan: "#7FC1B8",
    white: "#D6DFE3",
    brightBlack: "#7F909A",
    brightRed: "#EFA39C",
    brightGreen: "#BCD08E",
    brightYellow: "#E6CB86",
    brightBlue: "#A9CFE0",
    brightMagenta: "#DAB6DF",
    brightCyan: "#9BD3CB",
    brightWhite: "#F1F5F7",
  },
};
